name: "Run CI Tasks"

on:
  workflow_dispatch:
  pull_request:
  push:
    tags: ["*"]
    branches: ["main"]
  schedule:
    - cron: "0 5 * * *"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

env:
  MISE_EXPERIMENTAL: true

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "jdx/mise-action@v2"
      - run: "mise run ci"
        env:
          DEVCONTAINER_GITHUB_TOKEN: "${{ secrets.DEVCONTAINER_GITHUB_TOKEN }}"
